name: Lint

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 1 * *  # monthly
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run pre-commit
        uses: tox-dev/action-pre-commit-uv@v1
