name: Build and Release Wheels

on:
  push:

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }} (${{ matrix.platform }}-${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: manylinux
            arch: x86_64
          - os: ubuntu-24.04-arm
            platform: manylinux
            arch: aarch64
          - os: ubuntu-latest
            platform: musllinux
            arch: x86_64
          - os: ubuntu-24.04-arm
            platform: musllinux
            arch: aarch64
          - os: macos-15-intel
            platform: macos
            arch: x86_64
          - os: macos-latest
            platform: macos
            arch: arm64
          - os: windows-latest
            platform: win
            arch: AMD64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up MSYS2 (Windows)
        if: runner.os == 'Windows'
        id: msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          path-type: minimal
          install: >-
            base-devel
          pacboy: >-
            toolchain:p

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.1
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: cp310-${{ matrix.platform }}*
          CIBW_ENVIRONMENT_WINDOWS: >
            PATH='${{ steps.msys2.outputs.msys2-location }}\ucrt64\bin;${{ steps.msys2.outputs.msys2-location }}\usr\bin;$PATH'
            MSYSTEM=UCRT64
            CHERE_INVOKING=1
            CC=gcc
            CXX=g++
            AR=ar
            RANLIB=ranlib

      - uses: actions/upload-artifact@v7
        with:
          name: wheels-${{ matrix.platform }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
